# The URL the site will be built for
base_url = "https://fpqyv-5iaaa-aaaah-qc3ha-cai.ic0.app"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

title = "manue1'blog"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "archie-zola"

taxonomies = [
    {name = "tags"}
]

default_language = "en"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
# control dark mode: auto | dark | toggle
mode = "auto"

# # subtitle will show under the title in index page
# subtitle = "A zola theme forked from [archie](https://github.com/athul/archie)"

# if set true, will use external CDN resource to load font and js file
useCDN = true

favicon = "/icon/favicon.png"

# show in the footer
copyright = "manue1"

# config your Google Analysis ID
ga = "G-6EYH6VQ7BE"


# config multi-language menu and other text
[[extra.translations.en]]
show_more = "Read more ⟶"
previous_page = "← Previous"
next_page = "Next →"
posted_on = "on "
posted_by = "Published by"
read_time = "minute read"
all_tags = "All tags"
menus = [
    { name = "Home", url = "/index.html", weight = 4},
    { name = "All posts", url = "/posts/index.html", weight = 4 },
    { name = "About", url = "/about/index.html", weight = 4 },
    { name = "Tags", url = "/tags/index.html", weight = 4 },
]

# config social icon info in the footer
[[extra.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/nanue1"

[[extra.social]]
icon = "twitter"
name = "Twitter"
url = "https://twitter.com/zimuchunzi0508"


